User get-version and rewrite most of the script

diff --git a/make-package-debian b/make-package-debian
--- a/make-package-debian
+++ b/make-package-debian
@@ -3,54 +3,79 @@
 # 2022/01/27 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 
 # For faster check-depends, binaries in coreutils, findutils, binutils, util-linux, debianutils, perl.
-## MetaBin: ar basename cat chmod cp cut du head id ln ls md5sum mkdir mktemp paste pod2html pod2man rm sed sort stat su tail touch xargs wc mv seq xz unxz
+## MetaBin: ar basename cat chmod cp cut du head id ln ls md5sum mkdir mktemp paste pod2html pod2man rm sed sort stat su tail touch xargs wc mv seq xz unxz awk
 
-trap '[ -n "${tmp_folder}" -a -d "${tmp_folder}" ] && rm -rf "${tmp_folder}"' QUIT
+set -euo pipefail
 
-export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
+# Clean at end of script in all case
+trap 'rm -rf "${tmp_folder:-}"' EXIT QUIT
+
+export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 export LANG=C
 
+# Check build commands
+for cmd in ar tar gzip pod2man mktemp du cut install
+do
+  command -v "$cmd" >/dev/null || {
+    echo "error: $cmd missing"
+    exit 1
+  }
+done
+
+# Temporary folder
 tmp_folder=$(mktemp --directory /tmp/oberapk-XXXXXX)
 [ -n "${tmp_folder}" ] && [ -d "${tmp_folder}" ] || exit 1
 
 # Set Name and Version
 PKG_NAME=oberapk
-CODE_VERSION=$(grep '^VERSION=' oberapk | cut -f 2 -d "'")
+CODE_VERSION=$(./get-version)
 PKG_VERSION=1
+[ -n "${CODE_VERSION}" ] || {
+  echo "error: Empty version"
+  exit 1
+}
 
-# Create future tree
-mkdir -p "${tmp_folder}/usr/bin"
-mkdir -p "${tmp_folder}/usr/share/man/man1"
-mkdir -p "${tmp_folder}/usr/share/oberapk"
-mkdir -p "${tmp_folder}/usr/lib/oberapk/pakaj.d"
-mkdir -p "${tmp_folder}/etc/oberapk"
-mkdir -p "${tmp_folder}/etc/cron.daily"
-mkdir -p "${tmp_folder}/etc/cron.weekly"
-mkdir -p "${tmp_folder}/etc/bash_completion.d"
-cp oberapk                   "${tmp_folder}/usr/bin/"
-pod2man oberapk.pod | gzip > "${tmp_folder}/usr/share/man/man1/oberapk.1.gz" # Manual
-cp LICENSE.md                "${tmp_folder}/usr/share/oberapk/"
-cp AUTHORS.md                "${tmp_folder}/usr/share/oberapk/"
-cp COPYRIGHT.md              "${tmp_folder}/usr/share/oberapk/"
-cp README.md                 "${tmp_folder}/usr/share/oberapk/"
-cp oberapk.sample.conf       "${tmp_folder}/usr/share/oberapk/"
-cp oberapk.sample.sh         "${tmp_folder}/usr/share/oberapk/"
-cp oberapk.sample.conf       "${tmp_folder}/etc/oberapk/"
-cp oberapk.sample.sh         "${tmp_folder}/etc/oberapk/"
-cp oberapk.bash_completion   "${tmp_folder}/etc/bash_completion.d/oberapk"
-cp cron.daily.sh             "${tmp_folder}/etc/cron.daily/oberapk"
-cp cron.weekly.sh            "${tmp_folder}/etc/cron.weekly/oberapk"
-cp pakaj.d/*.sh              "${tmp_folder}/usr/lib/oberapk/pakaj.d/"
-chmod -R a+rx        "${tmp_folder}/usr/bin/oberapk"
-chmod -R a+rX,go-w   "${tmp_folder}/usr"
-chmod -R a+rX,go-w   "${tmp_folder}/etc"
+# Transform version
+for f in oberapk oberapk.pod
+do
+  sed "s/@VERSION@/${CODE_VERSION}/g;" "${f}" > "${tmp_folder}/${f}"
+done
+
+# Install files
+install -Dm 0755 -t "${tmp_folder}"/usr/bin/                "${tmp_folder}"/oberapk
+install -Dm 0644 -t "${tmp_folder}"/usr/share/oberapk/      LICENSE.md AUTHORS.md COPYRIGHT.md README.md oberapk.sample.conf oberapk.sample.sh
+install -Dm 0644 -t "${tmp_folder}"/etc/oberapk/            oberapk.sample.conf oberapk.sample.sh
+for script in oberapk
+do
+  install -Dm 0644 "${script}".bash_completion "${tmp_folder}"/usr/share/bash-completion/completions/"${script}"
+done
+
+# Create manuals
+mkdir -p "${tmp_folder}"/usr/share/man/man1
+pod2man --section=1 --release="Oberapk ${CODE_VERSION}" "${tmp_folder}"/oberapk.pod    | gzip > "${tmp_folder}"/usr/share/man/man1/oberapk.1.gz
+
+# Cron
+mkdir -p "${tmp_folder}"/etc/cron.daily
+mkdir -p "${tmp_folder}"/etc/cron.weekly
+cp cron.daily.sh  "${tmp_folder}"/etc/cron.daily/oberapk
+cp cron.weekly.sh "${tmp_folder}"/etc/cron.weekly/oberapk
+
+# Action
+mkdir -p "${tmp_folder}"/usr/lib/oberapk/pakaj.d
+cp pakaj.d/*.sh   "${tmp_folder}"/usr/lib/oberapk/pakaj.d/
+
+# Good right
+chmod -R a+rX,go-w   "${tmp_folder}"/usr
+chmod -R a+rX,go-w   "${tmp_folder}"/etc
+
+# Package size
+PKG_SIZE=$(du -ks "${tmp_folder}"/usr "${tmp_folder}"/etc | awk '{sum += $1} END {print sum}')
 
 # Data archive
-rm -f "${tmp_folder}/data.tar.gz"
 (cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf data.tar.gz ./usr ./etc)
 
 # Control file
-cat <<END > "${tmp_folder}/control"
+cat <<END > "${tmp_folder}"/control
 Package: ${PKG_NAME}
 Version: ${CODE_VERSION}-${PKG_VERSION}
 Section: utils
@@ -59,21 +84,20 @@ Priority: optional
 Depends: bash, coreutils, findutils, binutils, util-linux, debianutils, tar, sed, grep, awk, wget, curl, reprepro, git, make, perl, gzip, unzip, xz-utils, file
 Recommends: apt-file
 Architecture: all
-Installed-Size: $(du -ks "${tmp_folder}"|cut -f 1)
+Installed-Size: "${PKG_SIZE}"
 Maintainer: Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 Description: wget Debian package and build simple package and push them on local reprepro
 Homepage: https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/oberapk
 END
 
 # Control archive
-rm -f "${tmp_folder}/control.tar.gz"
 (cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf control.tar.gz control)
 
 # Format deb package
-echo 2.0 > "${tmp_folder}/debian-binary"
+echo 2.0 > "${tmp_folder}"/debian-binary
 
 # Create package (control before data)
-ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb" "${tmp_folder}/debian-binary" "${tmp_folder}/control.tar.gz" "${tmp_folder}/data.tar.gz"
+ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}"_all.deb "${tmp_folder}"/debian-binary "${tmp_folder}"/control.tar.gz "${tmp_folder}"/data.tar.gz
       
 # Clean
 rm -rf "${tmp_folder}"
